version: '3.9'
services:
  postgres:
    image: postgres:13.6
    environment:
      POSTGRES_DB: 'test-crud'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5432:5432'
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql