definitions:
  httperr.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  ports.ListPostsResponse:
    properties:
      posts:
        items:
          $ref: '#/definitions/ports.Post'
        type: array
    type: object
  ports.Post:
    properties:
      body:
        type: string
      id:
        type: integer
      title:
        type: string
      user_id:
        type: integer
    type: object
  ports.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  ports.UpdatePostRequest:
    properties:
      body:
        type: string
      post_id:
        type: integer
      title:
        type: string
    type: object
info:
  contact:
    email: madaminovsbektosh@gmail.com
    name: Bektosh Madaminov
  description: This is a first version of Test CRUD APIs
  title: Test CRUD API
  version: "1.0"
paths:
  /api/posts:
    get:
      description: API for fetching a list of posts
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.ListPostsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: get list of posts
      tags:
      - posts
    put:
      description: API for updating post's info
      parameters:
      - description: post
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ports.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: update post info
      tags:
      - posts
  /api/posts/{post-id}:
    delete:
      description: API for deleting a post
      parameters:
      - description: post-id
        in: path
        name: post-id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: delete a post
      tags:
      - posts
    get:
      description: API for fetching an individual post
      parameters:
      - description: post-id
        in: path
        name: post-id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.Post'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: get individual post
      tags:
      - posts
  /api/posts/download:
    post:
      description: API for starting the download of posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: start downloading posts
      tags:
      - posts
  /api/posts/download/status:
    get:
      description: API for checking the status of posts download
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.ErrorResponse'
      summary: report back status of downloading posts
      tags:
      - posts
swagger: "2.0"
